### ISSUE TITLE
UX: Definir los Layout para los dispositivos (mobile, tablet, desktop) en figma

### ISSUE THREAD

**Issue by LicetLemus** [LicetLemus/DEV015-dataverse#14]
- [x] Definir Layout para mobile
- [ ] Definir Layout para Tablet (horizontal y vertical)
- [ ] Definir Layout para Desktop

**Comment by abengl** [comment]
Testing, I am adding a comment to check if @LicetLemus can assign it to me.

**Comment by abengl** [comment]
Trabajos en equipo para pulir el la layout para móvil: [Figma](https://www.figma.com/design/PRBukRP40w0dqTphu9ZA5M/Dataverse-Prototipo?node-id=77-33&t=9UkuBJcdL1hTKg5s-1).
