### ISSUE TITLE
Styles: Investigar y definir el estilo de background, footer, header, card

### ISSUE THREAD

**Issue by LicetLemus** [LicetLemus/DEV015-dataverse#25]
Definir la ubicación o mejoras de las label en las card

**Comment by abengl** [comment]
- [x] Selección de una web modelo para los estilos -> https://pitch.com/pitch-to-win/2023/design
- [x] Aplicar los estilos a la versión desktop: header (logo y nombre), hero section (background, title, description), backrground, tarjetas (labels, icons, image, text) y footer.
@LicetLemus 
Se plantea como alternativa el reemplazo del ícono de dificultad por una etiqueta ya que noto mayor armonía en el diseño.
![image](https://github.com/LicetLemus/DEV015-dataverse/assets/126703861/9b4bdef1-aeb9-482d-ac4e-00c64646e671)
![image](https://github.com/LicetLemus/DEV015-dataverse/assets/126703861/65b3fa7e-afa3-4535-b2f2-a5c6c362d687)

**Comment by abengl** [comment]
- [x] Acordamos trabajar con labes para los iconos de dificultad.
