### ISSUE TITLE
UX/UI: Flujo de test de usabilidad para prototipo desktop

### ISSUE THREAD

**Issue by LicetLemus** [LicetLemus/DEV015-dataverse#28]
- Buscar los participantes (2) 
- Realizar los conclusiones del test (feedback)

**Comment by abengl** [comment]
- [x] Prototipo con flow para desktop listo para test de usabilidad: [LINK](https://www.figma.com/proto/PRBukRP40w0dqTphu9ZA5M/Dataverse-Prototipo?node-id=118-990&t=3ncuh6xTUH0EPuHB-1&scaling=min-zoom&content-scaling=fixed&page-id=118%3A988&starting-point-node-id=118%3A990)
@LicetLemus:
-  Se plantea como opción mostrar las etiquetas de tipo, campo de aplicació, dificultad y el logo del lenguage de programación cuando se haga un hover sobre la tarjeta o al hacer click sobre ella. De momento está habilitado en el prototipo al hacer hover. 👀 
 
[Screencast from 06-13-2024 08:18:50 AM.webm](https://github.com/LicetLemus/DEV015-dataverse/assets/126703861/f5118cff-a205-4fda-974d-c1a6c449782c)

**Comment by abengl** [comment]
- [x] Habilitar los flows para los botones de navegación: filtro tipo, filtro de aplicación, limpiar y ránking.
