### ISSUE TITLE
UX/UI: Realizar el flujo de test de usabilidad para mobile 

### ISSUE THREAD

**Issue by LicetLemus** [LicetLemus/DEV015-dataverse#29]
- Buscar los participantes (2)
- Realizar los conclusiones del test (feedback)

**Comment by abengl** [comment]
- Versión móvil: https://www.figma.com/proto/PRBukRP40w0dqTphu9ZA5M/Dataverse-Prototipo?node-id=304-1759&t=rSZbGyusdCnb7Zfr-1&scaling=scale-down&content-scaling=fixed&page-id=77%3A33&starting-point-node-id=304%3A1759
