### ISSUE TITLE
CSS: Ajuste de estilos de acuerdo al feedback recibido en el test de usabilidad

### ISSUE THREAD

**Issue by LicetLemus** [LicetLemus/DEV015-dataverse#36]
- [x]  Ajuste para desktop:
- [x] Estática: background web/tarjetas.
- [x] Dinámica: Navegación, efectos.
- [x] Acomodar las labels en las tarjetas para una interfaz más clara.

**Comment by abengl** [comment]
https://www.notion.so/abengl/Test-de-Usabilidad-7a6a039a1ae0438b9350f426f507d832

**Comment by abengl** [comment]
✅Reducir la sombra cuando las tarjetas están en el main y aumentarla cuando se hace hover/tap
🤔 Agregar un efecto al aplicar un filtro u orden para que se realce el cambio.
🤔 Reubicar los iconos en el container de texto para mostrarlo en una sola vista.
