### ISSUE TITLE
Styles: Mejoras en las cards

### ISSUE THREAD

**Issue by LicetLemus** [LicetLemus/DEV015-dataverse#53]
- [x] Ajustar el footer de las card (icon de las label)
- [x] Mejorar el bold de etiquetas span (año y autor)
- [x] Añadir los logos al lado del nombre
- [x] Resolver como se van a ver las imagenes (background)  si se les aplica un filtro, si se cambia la posición de algunas tarjetas, etc.
- [x] Vista de la card a mostrar en el ranking y como hacer para indicar el click (cursor, emojis, etc)

**Comment by abengl** [comment]
Hi @LicetLemus aquí unos recursos para el efecto hover:
https://youtu.be/EOPpgs226cg?si=frl-SWagV1f4sN_S
https://youtu.be/JCxFPavlcbA?si=j5h3e-xFKAqGnSgL
https://youtu.be/c-6XRnYHbkw?si=VXs0eYq7yjF0t-nw
